[package]
name = "robohome_daily_updater"
version = "0.1.0"
authors = ["Robert Masen <r@robertmasen.pizza>"]

[dependencies]
robohome_shared = { path = "../shared" }
log = "0.4.5"
env_logger = "0.5.13"